namespace NLink.Core.ScreenShare;

public sealed record ScreenShareMetrics(
    long FramesCaptured = 0,
    long FramesQueued = 0,
    long FramesDropped = 0,
    long FramesDroppedByRateGate = 0,
    long FramesDroppedByQueueEvict = 0,
    long ChunksSent = 0,
    long RawFrameBytesSent = 0,
    long SerializedChunkBytesSent = 0,
    long BridgeBytesSent = 0,
    long FramesCompleted = 0,
    long FramesRejectedOversize = 0,
    long FramesDecoded = 0,
    long DecodeErrors = 0,
    long FramesCoalesced = 0,
    long DisplayInfoSendCount = 0,
    long LastCaptureToSendAgeMs = -1,
    double AverageCaptureToEnqueueMs = 0,
    double AverageEnqueueToSendMs = 0,
    double AverageCaptureToSendMs = 0,
    long StaleFrameRenders = 0,
    double AverageRenderIntervalMs = 0,
    double AverageCaptureToRenderMs = 0,
    bool TransferDownshiftActive = false,
    long TransferDownshiftFramesSuppressed = 0);
