function Write-SoakDiagnosticsArtifacts {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [Parameter(Mandatory = $true)]$Summary
    )

    $artifactRoot = Join-Path $RepoRoot 'artifacts\soak'
    $artifactDir = Join-Path $artifactRoot (Get-Date -Format 'yyyyMMdd-HHmmss')
    New-Item -ItemType Directory -Path $artifactDir -Force | Out-Null

    $helperDecodeWorkerSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("frames_completed={0}" -f $Summary.LatestHelperFramesCompleted),
        ("frames_enqueued_for_decode={0}" -f $Summary.LatestHelperFramesEnqueuedForDecode),
        ("frames_dropped_before_decode={0}" -f $Summary.LatestHelperFramesDroppedBeforeDecode),
        ("frames_decoded={0}" -f $Summary.LatestHelperFramesDecoded),
        ("frames_dropped_after_decode={0}" -f $Summary.LatestHelperFramesDroppedAfterDecode),
        ("frames_applied={0}" -f $Summary.LatestHelperFramesApplied),
        ("max_pending_encoded_depth={0}" -f $Summary.LatestHelperMaxPendingEncodedDepth),
        ("max_pending_decoded_depth={0}" -f $Summary.LatestHelperMaxPendingDecodedDepth),
        ("avg_enqueue_to_decode_start_ms={0}" -f $Summary.LatestHelperAvgEnqueueToDecodeStartMs),
        ("avg_enqueue_to_drop_ms={0}" -f $Summary.LatestHelperAvgEnqueueToDropMs),
        ("decode_worker_drop_queue_overflow_count={0}" -f $Summary.LatestHelperDecodeWorkerDropQueueOverflowCount),
        ("decode_worker_drop_age_budget_count={0}" -f $Summary.LatestHelperDecodeWorkerDropAgeBudgetCount),
        ("decode_worker_drop_generation_count={0}" -f $Summary.LatestHelperDecodeWorkerDropGenerationCount),
        ("decode_worker_drop_stopped_count={0}" -f $Summary.LatestHelperDecodeWorkerDropStoppedCount),
        ("decode_queue_overflow_count={0}" -f $Summary.LatestHelperDecodeQueueOverflowCount),
        ("decode_age_budget_count={0}" -f $Summary.LatestHelperDecodeAgeBudgetCount),
        ("decode_generation_changed_count={0}" -f $Summary.LatestHelperDecodeGenerationChangedCount),
        ("decode_stopped_count={0}" -f $Summary.LatestHelperDecodeStoppedCount),
        ("decoded_apply_queue_overflow_count={0}" -f $Summary.LatestHelperDecodedApplyQueueOverflowCount),
        ("decoded_frame_replaced_before_apply_count={0}" -f $Summary.LatestHelperDecodedFrameReplacedBeforeApplyCount),
        ("stale_dropped_after_decode_count={0}" -f $Summary.LatestHelperStaleDroppedAfterDecodeCount),
        ("dropped_waiting_for_recovery_keyframe_count={0}" -f $Summary.LatestHelperDroppedWaitingForRecoveryKeyframeCount),
        ("waiting_for_recovery_keyframe_reject_count={0}" -f $Summary.LatestHelperWaitingForRecoveryKeyframeRejectCount),
        ("recovery_wait_reject_before_runway_count={0}" -f $Summary.LatestHelperRecoveryWaitRejectBeforeRunwayCount),
        ("recovery_runway_overflow_reject_count={0}" -f $Summary.LatestHelperRecoveryRunwayOverflowRejectCount),
        ("suppressed_emit_during_recovery_wait_count={0}" -f $Summary.LatestHelperSuppressedEmitDuringRecoveryWaitCount),
        ("stale_superseded_recovery_suppressed_count={0}" -f $Summary.LatestHelperStaleSupersededRecoverySuppressedCount),
        ("soft_stale_cleanup_count={0}" -f $Summary.LatestHelperSoftStaleCleanupCount),
        ("blocked_by_reserved_recovery_frame_reject_count={0}" -f $Summary.LatestHelperBlockedByReservedRecoveryFrameRejectCount),
        ("older_epoch_ignored_during_recovery_lock_count={0}" -f $Summary.LatestHelperOlderEpochIgnoredDuringRecoveryLockCount),
        ("newer_epoch_non_key_ignored_during_lock_count={0}" -f $Summary.LatestHelperNewerEpochNonKeyIgnoredDuringLockCount),
        ("deferred_post_recovery_candidate_replace_count={0}" -f $Summary.LatestHelperDeferredPostRecoveryCandidateReplaceCount),
        ("future_tail_quarantined_during_gap_count={0}" -f $Summary.LatestHelperFutureTailQuarantinedDuringGapCount),
        ("future_tail_quarantined_after_gap_count={0}" -f $Summary.LatestHelperFutureTailQuarantinedAfterGapCount),
        ("pre_candidate_gap_tail_rejected_count={0}" -f $Summary.LatestHelperPreCandidateGapTailRejectedCount),
        ("recovery_candidate_present_count={0}" -f $Summary.LatestHelperRecoveryCandidatePresentCount),
        ("visible_recovery_floor_frame_id={0}" -f $Summary.LatestHelperVisibleRecoveryFloorFrameId),
        ("stable_visible_head_frame_id={0}" -f $Summary.LatestHelperStableVisibleHeadFrameId),
        ("applied_head_frame_id={0}" -f $Summary.LatestHelperAppliedHeadFrameId),
        ("visible_head_frame_id={0}" -f $Summary.LatestHelperVisibleHeadFrameId),
        ("ordered_emit_head_frame_id={0}" -f $Summary.LatestHelperOrderedEmitHeadFrameId),
        ("winning_recovery_frame_id={0}" -f $Summary.LatestHelperWinningRecoveryFrameId),
        ("recovery_owner_replaced_count={0}" -f $Summary.LatestHelperRecoveryOwnerReplacedCount),
        ("older_epoch_cleanup_after_epoch_advance_count={0}" -f $Summary.LatestHelperOlderEpochCleanupAfterEpochAdvanceCount),
        ("superseded_recovery_tail_cleanup_count={0}" -f $Summary.LatestHelperSupersededRecoveryTailCleanupCount),
        ("late_same_epoch_after_head_advanced_drop_count={0}" -f $Summary.LatestHelperLateSameEpochAfterHeadAdvancedDropCount),
        ("stale_runway_window_abort_count={0}" -f $Summary.LatestHelperStaleRunwayWindowAbortCount),
        ("runway_candidate_expired_after_head_advance_count={0}" -f $Summary.LatestHelperRunwayCandidateExpiredAfterHeadAdvanceCount),
        ("runway_followers_emitted_within_actionable_window_count={0}" -f $Summary.LatestHelperRunwayFollowersEmittedWithinActionableWindowCount),
        ("steady_visible_progress_active={0}" -f $Summary.LatestHelperSteadyVisibleProgressActive),
        ("steady_visible_progress_activation_frame_id={0}" -f $Summary.LatestHelperSteadyVisibleProgressActivationFrameId),
        ("frames_applied_since_last_gap={0}" -f $Summary.LatestHelperFramesAppliedSinceLastGap),
        ("last_sent_stable_visible_head_frame_id={0}" -f $Summary.LatestHelperLastSentStableVisibleHeadFrameId),
        ("steady_visible_progress_cleared_count={0}" -f $Summary.LatestHelperSteadyVisibleProgressClearedCount),
        ("steady_visible_progress_cleared_reason={0}" -f $Summary.LatestHelperSteadyVisibleProgressClearedReason),
        ("pre_candidate_gap_tail_emitted_to_viewer_count={0}" -f $Summary.LatestHelperPreCandidateGapTailEmittedToViewerCount),
        ("late_fragment_after_applied_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterAppliedHeadCount),
        ("late_fragment_after_ordered_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterOrderedHeadCount),
        ("late_fragment_after_stable_visible_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterStableVisibleHeadCount),
        ("late_fragment_after_visible_recovery_count={0}" -f $Summary.LatestHelperLateFragmentAfterVisibleRecoveryCount),
        ("actionable_late_fragment_count={0}" -f $Summary.LatestHelperActionableLateFragmentCount),
        ("recovery_runway_contiguous_follower_buffer_count={0}" -f $Summary.LatestHelperRecoveryRunwayContiguousFollowerBufferCount),
        ("recovery_runway_contiguous_follower_apply_count={0}" -f $Summary.LatestHelperRecoveryRunwayContiguousFollowerApplyCount),
        ("recovery_runway_abort_count={0}" -f $Summary.LatestHelperRecoveryRunwayAbortCount),
        ("recovery_follower_window_buffered_count={0}" -f $Summary.LatestHelperRecoveryFollowerWindowBufferedCount),
        ("recovery_follower_window_applied_count={0}" -f $Summary.LatestHelperRecoveryFollowerWindowAppliedCount),
        ("recovery_follower_window_trimmed_count={0}" -f $Summary.LatestHelperRecoveryFollowerWindowTrimmedCount),
        ("protected_recovery_delivery_count={0}" -f $Summary.LatestHelperProtectedRecoveryDeliveryCount),
        ("recovery_progress_corridor_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorCount),
        ("recovery_progress_corridor_success_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorSuccessCount),
        ("recovery_progress_corridor_abort_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorAbortCount),
        ("recovery_progress_corridor_applied_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorAppliedCount),
        ("recovery_keyframe_pending_visible_apply_count={0}" -f $Summary.LatestHelperRecoveryKeyframePendingVisibleApplyCount),
        ("startup_corridor_buffered_follower_count={0}" -f $Summary.LatestHelperStartupCorridorBufferedFollowerCount),
        ("startup_corridor_release_count={0}" -f $Summary.LatestHelperStartupCorridorReleaseCount),
        ("startup_corridor_abort_count={0}" -f $Summary.LatestHelperStartupCorridorAbortCount),
        ("startup_corridor_abort_reason={0}" -f $Summary.LatestHelperStartupCorridorAbortReason),
        ("post_recovery_visible_generation_reset_count={0}" -f $Summary.LatestHelperPostRecoveryVisibleGenerationResetCount),
        ("post_recovery_purged_pre_recovery_follower_count={0}" -f $Summary.LatestHelperPostRecoveryPurgedPreRecoveryFollowerCount),
        ("post_recovery_stale_drop_bypass_count={0}" -f $Summary.LatestHelperPostRecoveryStaleDropBypassCount),
        ("late_fragment_after_successful_recovery_count={0}" -f $Summary.LatestHelperLateFragmentAfterSuccessfulRecoveryCount),
        ("post_recovery_high_frame_age_suppressed_ticks={0}" -f $Summary.AggregatePostRecoveryHighFrameAgeSuppressedTicks),
        ("dominant_helper_admission_reject_reason={0}" -f $Summary.LatestHelperDominantAdmissionRejectReason),
        ("high_frame_age_suppressed_due_to_visible_progress_count={0}" -f $Summary.AggregateHighFrameAgeSuppressedDueToVisibleProgressCount),
        ("high_frame_age_suppressed_due_to_head_advance_count={0}" -f $Summary.LatestHelperHighFrameAgeSuppressedDueToHeadAdvanceCount),
        ("actionable_high_frame_age_count={0}" -f $Summary.LatestHelperActionableHighFrameAgeCount),
        ("unattributed_loss_count={0}" -f $Summary.LatestHelperUnattributedLossCount),
        '',
        'helper_epoch_loss_lines:'
    ) + @($Summary.HelperEpochLossLines)

    $helperQualitySummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("visible_apply_ratio={0}" -f $Summary.LatestHelperVisibleApplyRatio),
        ("helper_apply_ms_avg={0}" -f $Summary.HelperApplyAvgMs),
        ("helper_apply_ms_p95={0}" -f $Summary.HelperApplyP95Ms),
        ("avg_decode_complete_to_visible_apply_ms={0}" -f $Summary.LatestHelperAvgDecodeCompleteToVisibleApplyMs),
        ("avg_ui_post_apply_ms={0}" -f $Summary.LatestHelperAvgUiPostApplyMs),
        ("avg_visible_head_lag_frames={0}" -f $Summary.LatestHelperAvgVisibleHeadLagFrames),
        ("avg_stable_head_lag_frames={0}" -f $Summary.LatestHelperAvgStableHeadLagFrames),
        ("last_reserved_apply_hold_ms={0}" -f $Summary.LatestHelperLastReservedApplyHoldMs),
        ("last_recovery_progress_corridor_hold_ms={0}" -f $Summary.LatestHelperLastRecoveryProgressCorridorHoldMs),
        ("last_recovery_runway_abort_hold_ms={0}" -f $Summary.LatestHelperLastRecoveryRunwayAbortHoldMs),
        ("last_recovery_progress_corridor_abort_reason={0}" -f $Summary.LatestHelperLastRecoveryProgressCorridorAbortReason),
        ("reassembler_loss_count={0}" -f $Summary.LatestHelperReassemblerLossCount),
        ("gap_count={0}" -f $Summary.LatestHelperGapCount),
        ("recovery_keyframe_apply_count={0}" -f $Summary.LatestHelperRecoveryKeyframeApplyCount),
        ("resync_count={0}" -f $Summary.LatestHelperResyncCount),
        ("dominant_reassembler_root_cause={0}" -f $Summary.DominantReassemblerRootCause),
        ("dominant_helper_admission_reject_reason={0}" -f $Summary.LatestHelperDominantAdmissionRejectReason),
        ("recovery_wait_reject_before_runway_count={0}" -f $Summary.LatestHelperRecoveryWaitRejectBeforeRunwayCount),
        ("recovery_runway_overflow_reject_count={0}" -f $Summary.LatestHelperRecoveryRunwayOverflowRejectCount),
        ("suppressed_emit_during_recovery_wait_count={0}" -f $Summary.LatestHelperSuppressedEmitDuringRecoveryWaitCount),
        ("stale_superseded_recovery_suppressed_count={0}" -f $Summary.LatestHelperStaleSupersededRecoverySuppressedCount),
        ("soft_stale_cleanup_count={0}" -f $Summary.LatestHelperSoftStaleCleanupCount),
        ("pre_candidate_gap_tail_emitted_to_viewer_count={0}" -f $Summary.LatestHelperPreCandidateGapTailEmittedToViewerCount),
        ("recovery_candidate_present_count={0}" -f $Summary.LatestHelperRecoveryCandidatePresentCount),
        ("visible_recovery_floor_frame_id={0}" -f $Summary.LatestHelperVisibleRecoveryFloorFrameId),
        ("stable_visible_head_frame_id={0}" -f $Summary.LatestHelperStableVisibleHeadFrameId),
        ("applied_head_frame_id={0}" -f $Summary.LatestHelperAppliedHeadFrameId),
        ("visible_head_frame_id={0}" -f $Summary.LatestHelperVisibleHeadFrameId),
        ("ordered_emit_head_frame_id={0}" -f $Summary.LatestHelperOrderedEmitHeadFrameId),
        ("winning_recovery_frame_id={0}" -f $Summary.LatestHelperWinningRecoveryFrameId),
        ("recovery_owner_replaced_count={0}" -f $Summary.LatestHelperRecoveryOwnerReplacedCount),
        ("older_epoch_cleanup_after_epoch_advance_count={0}" -f $Summary.LatestHelperOlderEpochCleanupAfterEpochAdvanceCount),
        ("late_same_epoch_after_head_advanced_drop_count={0}" -f $Summary.LatestHelperLateSameEpochAfterHeadAdvancedDropCount),
        ("stale_runway_window_abort_count={0}" -f $Summary.LatestHelperStaleRunwayWindowAbortCount),
        ("runway_candidate_expired_after_head_advance_count={0}" -f $Summary.LatestHelperRunwayCandidateExpiredAfterHeadAdvanceCount),
        ("runway_followers_emitted_within_actionable_window_count={0}" -f $Summary.LatestHelperRunwayFollowersEmittedWithinActionableWindowCount),
        ("steady_visible_progress_active={0}" -f $Summary.LatestHelperSteadyVisibleProgressActive),
        ("frames_applied_since_last_gap={0}" -f $Summary.LatestHelperFramesAppliedSinceLastGap),
        ("pre_candidate_gap_tail_rejected_count={0}" -f $Summary.LatestHelperPreCandidateGapTailRejectedCount),
        ("late_fragment_after_applied_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterAppliedHeadCount),
        ("late_fragment_after_ordered_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterOrderedHeadCount),
        ("late_fragment_after_stable_visible_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterStableVisibleHeadCount),
        ("late_fragment_after_visible_recovery_count={0}" -f $Summary.LatestHelperLateFragmentAfterVisibleRecoveryCount),
        ("actionable_late_fragment_count={0}" -f $Summary.LatestHelperActionableLateFragmentCount),
        ("dominant_helper_pressure_blocker={0}" -f $Summary.DominantHelperPressureBlocker),
        ("baseline_established={0}" -f $Summary.LatestHelperBaselineEstablished),
        ("baseline_capture_to_render_ms={0}" -f $Summary.LatestHelperBaselineCaptureToRenderMs),
        ("age_excess_ms={0}" -f $Summary.LatestHelperAgeExcessMs),
        ("progress_stall_ms={0}" -f $Summary.LatestHelperProgressStallMs),
        ("baseline_reseed_in_progress={0}" -f $Summary.LatestHelperBaselineReseedInProgress),
        ("age_pressure_consecutive_count={0}" -f $Summary.LatestHelperAgePressureConsecutiveCount),
        ("cadence_pressure_consecutive_count={0}" -f $Summary.LatestHelperCadencePressureConsecutiveCount),
        ("post_recovery_age_grace_active={0}" -f $Summary.LatestPostRecoveryAgeGraceActive),
        ("post_recovery_age_grace_suppressed_count={0}" -f $Summary.LatestPostRecoveryAgeGraceSuppressedCount),
        ("catch_up_suppressed_due_to_progress_count={0}" -f $Summary.LatestHelperCatchUpSuppressedDueToProgressCount),
        ("baseline_frozen_due_to_stall_count={0}" -f $Summary.LatestHelperBaselineFrozenDueToStallCount),
        ("baseline_reseed_after_recovery_count={0}" -f $Summary.LatestHelperBaselineReseedAfterRecoveryCount),
        ("cadence_stall_window_count={0}" -f $Summary.LatestHelperCadenceStallWindowCount),
        ("cadence_stall_trigger_count={0}" -f $Summary.LatestHelperCadenceStallTriggerCount),
        ("high_frame_age_suppressed_due_to_visible_progress_count={0}" -f $Summary.AggregateHighFrameAgeSuppressedDueToVisibleProgressCount),
        ("high_frame_age_suppressed_due_to_head_advance_count={0}" -f $Summary.LatestHelperHighFrameAgeSuppressedDueToHeadAdvanceCount),
        ("actionable_high_frame_age_count={0}" -f $Summary.LatestHelperActionableHighFrameAgeCount),
        ("worst_epoch_by_visible_apply_ratio={0}" -f $Summary.WorstEpochByVisibleApplyRatio),
        ("worst_epoch_visible_apply_ratio={0}" -f $Summary.WorstEpochVisibleApplyRatio),
        ("worst_epoch_by_recovery_lock_time={0}" -f $Summary.WorstEpochByRecoveryLockTime),
        ("worst_epoch_recovery_lock_time_ms={0}" -f $Summary.WorstEpochRecoveryLockTimeMs),
        ("recovery_follower_window_buffered_count={0}" -f $Summary.LatestHelperRecoveryFollowerWindowBufferedCount),
        ("recovery_follower_window_applied_count={0}" -f $Summary.LatestHelperRecoveryFollowerWindowAppliedCount),
        ("recovery_runway_contiguous_follower_buffer_count={0}" -f $Summary.LatestHelperRecoveryRunwayContiguousFollowerBufferCount),
        ("recovery_runway_contiguous_follower_apply_count={0}" -f $Summary.LatestHelperRecoveryRunwayContiguousFollowerApplyCount),
        ("recovery_runway_abort_count={0}" -f $Summary.LatestHelperRecoveryRunwayAbortCount),
        ("recovery_progress_corridor_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorCount),
        ("recovery_progress_corridor_success_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorSuccessCount),
        ("recovery_progress_corridor_abort_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorAbortCount),
        ("recovery_progress_corridor_applied_count={0}" -f $Summary.LatestHelperRecoveryProgressCorridorAppliedCount),
        ("recovery_keyframe_pending_visible_apply_count={0}" -f $Summary.LatestHelperRecoveryKeyframePendingVisibleApplyCount),
        ("startup_corridor_buffered_follower_count={0}" -f $Summary.LatestHelperStartupCorridorBufferedFollowerCount),
        ("startup_corridor_release_count={0}" -f $Summary.LatestHelperStartupCorridorReleaseCount),
        ("startup_corridor_abort_count={0}" -f $Summary.LatestHelperStartupCorridorAbortCount),
        ("startup_corridor_abort_reason={0}" -f $Summary.LatestHelperStartupCorridorAbortReason),
        ("recovery_follower_window_trimmed_count={0}" -f $Summary.LatestHelperRecoveryFollowerWindowTrimmedCount),
        ("protected_recovery_delivery_count={0}" -f $Summary.LatestHelperProtectedRecoveryDeliveryCount),
        ("recovery_post_ack_hold_active={0}" -f $Summary.LatestRecoveryPostAckHoldActive),
        ("recovery_post_ack_hold_started_count={0}" -f $Summary.LatestRecoveryPostAckHoldStartedCount),
        ("recovery_post_ack_hold_expired_count={0}" -f $Summary.LatestRecoveryPostAckHoldExpiredCount),
        ("recovery_post_ack_hold_suppressed_reopen_count={0}" -f $Summary.LatestRecoveryPostAckHoldSuppressedReopenCount),
        ("late_fragment_after_successful_recovery_count={0}" -f $Summary.LatestHelperLateFragmentAfterSuccessfulRecoveryCount),
        '',
        'helper_quality_summary_lines:'
    ) + @($Summary.HelperQualitySummaryLines)

    $helperUpstreamLatencySummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("capture_to_frame_ready_avg_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToFrameReadyAvgMs),
        ("capture_to_frame_ready_median_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToFrameReadyMedianMs),
        ("capture_to_frame_ready_p95_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToFrameReadyP95Ms),
        ("capture_to_frame_ready_max_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToFrameReadyMaxMs),
        ("frame_ready_to_viewer_accept_avg_ms={0}" -f $Summary.LatestHelperUpstreamFrameReadyToViewerAcceptAvgMs),
        ("frame_ready_to_viewer_accept_median_ms={0}" -f $Summary.LatestHelperUpstreamFrameReadyToViewerAcceptMedianMs),
        ("frame_ready_to_viewer_accept_p95_ms={0}" -f $Summary.LatestHelperUpstreamFrameReadyToViewerAcceptP95Ms),
        ("frame_ready_to_viewer_accept_max_ms={0}" -f $Summary.LatestHelperUpstreamFrameReadyToViewerAcceptMaxMs),
        ("viewer_accept_to_decode_enqueue_avg_ms={0}" -f $Summary.LatestHelperUpstreamViewerAcceptToDecodeEnqueueAvgMs),
        ("viewer_accept_to_decode_enqueue_median_ms={0}" -f $Summary.LatestHelperUpstreamViewerAcceptToDecodeEnqueueMedianMs),
        ("viewer_accept_to_decode_enqueue_p95_ms={0}" -f $Summary.LatestHelperUpstreamViewerAcceptToDecodeEnqueueP95Ms),
        ("viewer_accept_to_decode_enqueue_max_ms={0}" -f $Summary.LatestHelperUpstreamViewerAcceptToDecodeEnqueueMaxMs),
        ("decode_enqueue_to_decode_start_avg_ms={0}" -f $Summary.LatestHelperUpstreamDecodeEnqueueToDecodeStartAvgMs),
        ("decode_enqueue_to_decode_start_median_ms={0}" -f $Summary.LatestHelperUpstreamDecodeEnqueueToDecodeStartMedianMs),
        ("decode_enqueue_to_decode_start_p95_ms={0}" -f $Summary.LatestHelperUpstreamDecodeEnqueueToDecodeStartP95Ms),
        ("decode_enqueue_to_decode_start_max_ms={0}" -f $Summary.LatestHelperUpstreamDecodeEnqueueToDecodeStartMaxMs),
        ("capture_to_decode_start_avg_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToDecodeStartAvgMs),
        ("capture_to_decode_start_median_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToDecodeStartMedianMs),
        ("capture_to_decode_start_p95_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToDecodeStartP95Ms),
        ("capture_to_decode_start_max_ms={0}" -f $Summary.LatestHelperUpstreamCaptureToDecodeStartMaxMs),
        ("worst_epoch_by_capture_to_decode_start={0}" -f $Summary.LatestHelperUpstreamWorstEpochByCaptureToDecodeStart),
        ("worst_epoch_capture_to_decode_start_avg_ms={0}" -f $Summary.LatestHelperUpstreamWorstEpochCaptureToDecodeStartAvgMs),
        ("dominant_upstream_latency_stage={0}" -f $Summary.LatestHelperDominantUpstreamLatencyStage),
        ("helper_session_phase={0}" -f $(if ([string]::IsNullOrWhiteSpace($Summary.LatestSummaryHelperSessionPhase)) { '(none)' } else { $Summary.LatestSummaryHelperSessionPhase })),
        ("helper_recovery_mechanism={0}" -f $(if ([string]::IsNullOrWhiteSpace($Summary.LatestSummaryHelperRecoveryMechanism)) { '(none)' } else { $Summary.LatestSummaryHelperRecoveryMechanism })),
        '',
        'helper_upstream_latency_summary_lines:'
    ) + @($Summary.HelperUpstreamLatencySummaryLines)

    $helperReadyPathSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("capture_to_first_fragment_observed_avg_ms={0}" -f $Summary.LatestHelperReadyPathCaptureToFirstFragmentObservedAvgMs),
        ("capture_to_first_fragment_observed_median_ms={0}" -f $Summary.LatestHelperReadyPathCaptureToFirstFragmentObservedMedianMs),
        ("capture_to_first_fragment_observed_p95_ms={0}" -f $Summary.LatestHelperReadyPathCaptureToFirstFragmentObservedP95Ms),
        ("capture_to_first_fragment_observed_max_ms={0}" -f $Summary.LatestHelperReadyPathCaptureToFirstFragmentObservedMaxMs),
        ("first_fragment_to_last_fragment_observed_avg_ms={0}" -f $Summary.LatestHelperReadyPathFirstFragmentToLastFragmentObservedAvgMs),
        ("first_fragment_to_last_fragment_observed_median_ms={0}" -f $Summary.LatestHelperReadyPathFirstFragmentToLastFragmentObservedMedianMs),
        ("first_fragment_to_last_fragment_observed_p95_ms={0}" -f $Summary.LatestHelperReadyPathFirstFragmentToLastFragmentObservedP95Ms),
        ("first_fragment_to_last_fragment_observed_max_ms={0}" -f $Summary.LatestHelperReadyPathFirstFragmentToLastFragmentObservedMaxMs),
        ("last_fragment_to_assembly_complete_avg_ms={0}" -f $Summary.LatestHelperReadyPathLastFragmentToAssemblyCompleteAvgMs),
        ("last_fragment_to_assembly_complete_median_ms={0}" -f $Summary.LatestHelperReadyPathLastFragmentToAssemblyCompleteMedianMs),
        ("last_fragment_to_assembly_complete_p95_ms={0}" -f $Summary.LatestHelperReadyPathLastFragmentToAssemblyCompleteP95Ms),
        ("last_fragment_to_assembly_complete_max_ms={0}" -f $Summary.LatestHelperReadyPathLastFragmentToAssemblyCompleteMaxMs),
        ("assembly_complete_to_frame_emitted_avg_ms={0}" -f $Summary.LatestHelperReadyPathAssemblyCompleteToFrameEmittedAvgMs),
        ("assembly_complete_to_frame_emitted_median_ms={0}" -f $Summary.LatestHelperReadyPathAssemblyCompleteToFrameEmittedMedianMs),
        ("assembly_complete_to_frame_emitted_p95_ms={0}" -f $Summary.LatestHelperReadyPathAssemblyCompleteToFrameEmittedP95Ms),
        ("assembly_complete_to_frame_emitted_max_ms={0}" -f $Summary.LatestHelperReadyPathAssemblyCompleteToFrameEmittedMaxMs),
        ("dominant_ready_path_stage={0}" -f $Summary.LatestHelperDominantReadyPathStage),
        ("helper_session_phase={0}" -f $Summary.LatestSummaryHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestSummaryHelperRecoveryMechanism),
        '',
        'helper_ready_path_summary_lines:'
    ) + @($Summary.HelperReadyPathSummaryLines)

    $helperReceivePathSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("capture_to_envelope_send_avg_ms={0}" -f $Summary.LatestHelperReceivePathCaptureToEnvelopeSendAvgMs),
        ("capture_to_envelope_send_median_ms={0}" -f $Summary.LatestHelperReceivePathCaptureToEnvelopeSendMedianMs),
        ("capture_to_envelope_send_p95_ms={0}" -f $Summary.LatestHelperReceivePathCaptureToEnvelopeSendP95Ms),
        ("capture_to_envelope_send_max_ms={0}" -f $Summary.LatestHelperReceivePathCaptureToEnvelopeSendMaxMs),
        ("envelope_send_to_bridge_ingress_avg_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeSendToBridgeIngressAvgMs),
        ("envelope_send_to_bridge_ingress_median_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeSendToBridgeIngressMedianMs),
        ("envelope_send_to_bridge_ingress_p95_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeSendToBridgeIngressP95Ms),
        ("envelope_send_to_bridge_ingress_max_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeSendToBridgeIngressMaxMs),
        ("bridge_ingress_to_envelope_parsed_avg_ms={0}" -f $Summary.LatestHelperReceivePathBridgeIngressToEnvelopeParsedAvgMs),
        ("bridge_ingress_to_envelope_parsed_median_ms={0}" -f $Summary.LatestHelperReceivePathBridgeIngressToEnvelopeParsedMedianMs),
        ("bridge_ingress_to_envelope_parsed_p95_ms={0}" -f $Summary.LatestHelperReceivePathBridgeIngressToEnvelopeParsedP95Ms),
        ("bridge_ingress_to_envelope_parsed_max_ms={0}" -f $Summary.LatestHelperReceivePathBridgeIngressToEnvelopeParsedMaxMs),
        ("envelope_parsed_to_secure_decrypt_avg_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeParsedToSecureDecryptAvgMs),
        ("envelope_parsed_to_secure_decrypt_median_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeParsedToSecureDecryptMedianMs),
        ("envelope_parsed_to_secure_decrypt_p95_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeParsedToSecureDecryptP95Ms),
        ("envelope_parsed_to_secure_decrypt_max_ms={0}" -f $Summary.LatestHelperReceivePathEnvelopeParsedToSecureDecryptMaxMs),
        ("secure_decrypt_to_fragment_deserialize_avg_ms={0}" -f $Summary.LatestHelperReceivePathSecureDecryptToFragmentDeserializeAvgMs),
        ("secure_decrypt_to_fragment_deserialize_median_ms={0}" -f $Summary.LatestHelperReceivePathSecureDecryptToFragmentDeserializeMedianMs),
        ("secure_decrypt_to_fragment_deserialize_p95_ms={0}" -f $Summary.LatestHelperReceivePathSecureDecryptToFragmentDeserializeP95Ms),
        ("secure_decrypt_to_fragment_deserialize_max_ms={0}" -f $Summary.LatestHelperReceivePathSecureDecryptToFragmentDeserializeMaxMs),
        ("fragment_deserialize_to_first_fragment_observed_avg_ms={0}" -f $Summary.LatestHelperReceivePathFragmentDeserializeToFirstFragmentObservedAvgMs),
        ("fragment_deserialize_to_first_fragment_observed_median_ms={0}" -f $Summary.LatestHelperReceivePathFragmentDeserializeToFirstFragmentObservedMedianMs),
        ("fragment_deserialize_to_first_fragment_observed_p95_ms={0}" -f $Summary.LatestHelperReceivePathFragmentDeserializeToFirstFragmentObservedP95Ms),
        ("fragment_deserialize_to_first_fragment_observed_max_ms={0}" -f $Summary.LatestHelperReceivePathFragmentDeserializeToFirstFragmentObservedMaxMs),
        ("dominant_receive_path_stage={0}" -f $Summary.LatestHelperDominantReceivePathStage),
        ("helper_session_phase={0}" -f $Summary.LatestSummaryHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestSummaryHelperRecoveryMechanism),
        '',
        'helper_receive_path_summary_lines:'
    ) + @($Summary.HelperReceivePathSummaryLines)

    $helperBridgeIngressSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("envelope_send_to_bridge_message_observed_avg_ms={0}" -f $Summary.LatestHelperBridgeIngressEnvelopeSendToBridgeMessageObservedAvgMs),
        ("envelope_send_to_bridge_message_observed_median_ms={0}" -f $Summary.LatestHelperBridgeIngressEnvelopeSendToBridgeMessageObservedMedianMs),
        ("envelope_send_to_bridge_message_observed_p95_ms={0}" -f $Summary.LatestHelperBridgeIngressEnvelopeSendToBridgeMessageObservedP95Ms),
        ("envelope_send_to_bridge_message_observed_max_ms={0}" -f $Summary.LatestHelperBridgeIngressEnvelopeSendToBridgeMessageObservedMaxMs),
        ("bridge_message_observed_to_binary_frame_decoded_avg_ms={0}" -f $Summary.LatestHelperBridgeIngressBridgeMessageObservedToBinaryFrameDecodedAvgMs),
        ("bridge_message_observed_to_binary_frame_decoded_median_ms={0}" -f $Summary.LatestHelperBridgeIngressBridgeMessageObservedToBinaryFrameDecodedMedianMs),
        ("bridge_message_observed_to_binary_frame_decoded_p95_ms={0}" -f $Summary.LatestHelperBridgeIngressBridgeMessageObservedToBinaryFrameDecodedP95Ms),
        ("bridge_message_observed_to_binary_frame_decoded_max_ms={0}" -f $Summary.LatestHelperBridgeIngressBridgeMessageObservedToBinaryFrameDecodedMaxMs),
        ("binary_frame_decoded_to_bridge_ingress_avg_ms={0}" -f $Summary.LatestHelperBridgeIngressBinaryFrameDecodedToBridgeIngressAvgMs),
        ("binary_frame_decoded_to_bridge_ingress_median_ms={0}" -f $Summary.LatestHelperBridgeIngressBinaryFrameDecodedToBridgeIngressMedianMs),
        ("binary_frame_decoded_to_bridge_ingress_p95_ms={0}" -f $Summary.LatestHelperBridgeIngressBinaryFrameDecodedToBridgeIngressP95Ms),
        ("binary_frame_decoded_to_bridge_ingress_max_ms={0}" -f $Summary.LatestHelperBridgeIngressBinaryFrameDecodedToBridgeIngressMaxMs),
        ("dominant_bridge_ingress_stage={0}" -f $Summary.LatestHelperDominantBridgeIngressStage),
        ("helper_session_phase={0}" -f $Summary.LatestSummaryHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestSummaryHelperRecoveryMechanism),
        '',
        'helper_bridge_ingress_summary_lines:'
    ) + @($Summary.HelperBridgeIngressSummaryLines)

    $helperNknReceiveSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("envelope_send_to_sdk_handle_msg_entered_avg_ms={0}" -f $Summary.LatestHelperNknReceiveEnvelopeSendToSdkHandleMsgEnteredAvgMs),
        ("envelope_send_to_sdk_handle_msg_entered_median_ms={0}" -f $Summary.LatestHelperNknReceiveEnvelopeSendToSdkHandleMsgEnteredMedianMs),
        ("envelope_send_to_sdk_handle_msg_entered_p95_ms={0}" -f $Summary.LatestHelperNknReceiveEnvelopeSendToSdkHandleMsgEnteredP95Ms),
        ("envelope_send_to_sdk_handle_msg_entered_max_ms={0}" -f $Summary.LatestHelperNknReceiveEnvelopeSendToSdkHandleMsgEnteredMaxMs),
        ("sdk_handle_msg_entered_to_client_message_dispatch_avg_ms={0}" -f $Summary.LatestHelperNknReceiveSdkHandleMsgEnteredToClientMessageDispatchAvgMs),
        ("sdk_handle_msg_entered_to_client_message_dispatch_median_ms={0}" -f $Summary.LatestHelperNknReceiveSdkHandleMsgEnteredToClientMessageDispatchMedianMs),
        ("sdk_handle_msg_entered_to_client_message_dispatch_p95_ms={0}" -f $Summary.LatestHelperNknReceiveSdkHandleMsgEnteredToClientMessageDispatchP95Ms),
        ("sdk_handle_msg_entered_to_client_message_dispatch_max_ms={0}" -f $Summary.LatestHelperNknReceiveSdkHandleMsgEnteredToClientMessageDispatchMaxMs),
        ("client_message_dispatch_to_multiclient_message_dispatch_avg_ms={0}" -f $Summary.LatestHelperNknReceiveClientMessageDispatchToMultiClientMessageDispatchAvgMs),
        ("client_message_dispatch_to_multiclient_message_dispatch_median_ms={0}" -f $Summary.LatestHelperNknReceiveClientMessageDispatchToMultiClientMessageDispatchMedianMs),
        ("client_message_dispatch_to_multiclient_message_dispatch_p95_ms={0}" -f $Summary.LatestHelperNknReceiveClientMessageDispatchToMultiClientMessageDispatchP95Ms),
        ("client_message_dispatch_to_multiclient_message_dispatch_max_ms={0}" -f $Summary.LatestHelperNknReceiveClientMessageDispatchToMultiClientMessageDispatchMaxMs),
        ("multiclient_message_dispatch_to_bridge_message_observed_avg_ms={0}" -f $Summary.LatestHelperNknReceiveMultiClientMessageDispatchToBridgeMessageObservedAvgMs),
        ("multiclient_message_dispatch_to_bridge_message_observed_median_ms={0}" -f $Summary.LatestHelperNknReceiveMultiClientMessageDispatchToBridgeMessageObservedMedianMs),
        ("multiclient_message_dispatch_to_bridge_message_observed_p95_ms={0}" -f $Summary.LatestHelperNknReceiveMultiClientMessageDispatchToBridgeMessageObservedP95Ms),
        ("multiclient_message_dispatch_to_bridge_message_observed_max_ms={0}" -f $Summary.LatestHelperNknReceiveMultiClientMessageDispatchToBridgeMessageObservedMaxMs),
        ("dominant_nkn_receive_stage={0}" -f $Summary.LatestHelperDominantNknReceiveStage),
        ("helper_session_phase={0}" -f $Summary.LatestSummaryHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestSummaryHelperRecoveryMechanism),
        '',
        'helper_nkn_receive_summary_lines:'
    ) + @($Summary.HelperNknReceiveSummaryLines)

    $helperWsReceiveSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("envelope_send_to_ws_receiver_write_entered_avg_ms={0}" -f $Summary.LatestHelperWsReceiveEnvelopeSendToWsReceiverWriteEnteredAvgMs),
        ("envelope_send_to_ws_receiver_write_entered_median_ms={0}" -f $Summary.LatestHelperWsReceiveEnvelopeSendToWsReceiverWriteEnteredMedianMs),
        ("envelope_send_to_ws_receiver_write_entered_p95_ms={0}" -f $Summary.LatestHelperWsReceiveEnvelopeSendToWsReceiverWriteEnteredP95Ms),
        ("envelope_send_to_ws_receiver_write_entered_max_ms={0}" -f $Summary.LatestHelperWsReceiveEnvelopeSendToWsReceiverWriteEnteredMaxMs),
        ("ws_receiver_write_entered_to_ws_message_emitted_avg_ms={0}" -f $Summary.LatestHelperWsReceiveWsReceiverWriteEnteredToWsMessageEmittedAvgMs),
        ("ws_receiver_write_entered_to_ws_message_emitted_median_ms={0}" -f $Summary.LatestHelperWsReceiveWsReceiverWriteEnteredToWsMessageEmittedMedianMs),
        ("ws_receiver_write_entered_to_ws_message_emitted_p95_ms={0}" -f $Summary.LatestHelperWsReceiveWsReceiverWriteEnteredToWsMessageEmittedP95Ms),
        ("ws_receiver_write_entered_to_ws_message_emitted_max_ms={0}" -f $Summary.LatestHelperWsReceiveWsReceiverWriteEnteredToWsMessageEmittedMaxMs),
        ("ws_message_emitted_to_sdk_handle_msg_entered_avg_ms={0}" -f $Summary.LatestHelperWsReceiveWsMessageEmittedToSdkHandleMsgEnteredAvgMs),
        ("ws_message_emitted_to_sdk_handle_msg_entered_median_ms={0}" -f $Summary.LatestHelperWsReceiveWsMessageEmittedToSdkHandleMsgEnteredMedianMs),
        ("ws_message_emitted_to_sdk_handle_msg_entered_p95_ms={0}" -f $Summary.LatestHelperWsReceiveWsMessageEmittedToSdkHandleMsgEnteredP95Ms),
        ("ws_message_emitted_to_sdk_handle_msg_entered_max_ms={0}" -f $Summary.LatestHelperWsReceiveWsMessageEmittedToSdkHandleMsgEnteredMaxMs),
        ("dominant_ws_receive_stage={0}" -f $Summary.LatestHelperDominantWsReceiveStage),
        ("helper_session_phase={0}" -f $Summary.LatestSummaryHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestSummaryHelperRecoveryMechanism),
        '',
        'helper_ws_receive_summary_lines:'
    ) + @($Summary.HelperWsReceiveSummaryLines)

    $helperSocketReceiveSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("envelope_send_to_socket_data_event_emitted_avg_ms={0}" -f $Summary.LatestHelperSocketReceiveEnvelopeSendToSocketDataEventEmittedAvgMs),
        ("envelope_send_to_socket_data_event_emitted_median_ms={0}" -f $Summary.LatestHelperSocketReceiveEnvelopeSendToSocketDataEventEmittedMedianMs),
        ("envelope_send_to_socket_data_event_emitted_p95_ms={0}" -f $Summary.LatestHelperSocketReceiveEnvelopeSendToSocketDataEventEmittedP95Ms),
        ("envelope_send_to_socket_data_event_emitted_max_ms={0}" -f $Summary.LatestHelperSocketReceiveEnvelopeSendToSocketDataEventEmittedMaxMs),
        ("socket_data_event_emitted_to_ws_receiver_write_entered_avg_ms={0}" -f $Summary.LatestHelperSocketReceiveSocketDataEventEmittedToWsReceiverWriteEnteredAvgMs),
        ("socket_data_event_emitted_to_ws_receiver_write_entered_median_ms={0}" -f $Summary.LatestHelperSocketReceiveSocketDataEventEmittedToWsReceiverWriteEnteredMedianMs),
        ("socket_data_event_emitted_to_ws_receiver_write_entered_p95_ms={0}" -f $Summary.LatestHelperSocketReceiveSocketDataEventEmittedToWsReceiverWriteEnteredP95Ms),
        ("socket_data_event_emitted_to_ws_receiver_write_entered_max_ms={0}" -f $Summary.LatestHelperSocketReceiveSocketDataEventEmittedToWsReceiverWriteEnteredMaxMs),
        ("dominant_socket_receive_stage={0}" -f $Summary.LatestHelperDominantSocketReceiveStage),
        ("helper_session_phase={0}" -f $Summary.LatestSummaryHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestSummaryHelperRecoveryMechanism),
        '',
        'helper_socket_receive_summary_lines:'
    ) + @($Summary.HelperSocketReceiveSummaryLines)

    $bridgeEventLoopSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("event_loop_p95_ms={0}" -f $Summary.LatestBridgeEventLoopP95Ms),
        ("event_loop_max_ms={0}" -f $Summary.LatestBridgeEventLoopMaxMs),
        ("event_loop_mean_ms={0}" -f $Summary.LatestBridgeEventLoopMeanMs),
        ("sample_window_ms={0}" -f $Summary.LatestBridgeEventLoopSampleWindowMs),
        '',
        'bridge_event_loop_summary_lines:'
    ) + @($Summary.BridgeEventLoopSummaryLines)

    $bridgeMediaSendSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("binary_send_frame_observed_to_queue_enqueue_avg_ms={0}" -f $Summary.LatestBridgeMediaSendBinarySendFrameObservedToQueueEnqueueAvgMs),
        ("binary_send_frame_observed_to_queue_enqueue_median_ms={0}" -f $Summary.LatestBridgeMediaSendBinarySendFrameObservedToQueueEnqueueMedianMs),
        ("binary_send_frame_observed_to_queue_enqueue_p95_ms={0}" -f $Summary.LatestBridgeMediaSendBinarySendFrameObservedToQueueEnqueueP95Ms),
        ("binary_send_frame_observed_to_queue_enqueue_max_ms={0}" -f $Summary.LatestBridgeMediaSendBinarySendFrameObservedToQueueEnqueueMaxMs),
        ("queue_enqueue_to_queue_dequeue_avg_ms={0}" -f $Summary.LatestBridgeMediaSendQueueEnqueueToQueueDequeueAvgMs),
        ("queue_enqueue_to_queue_dequeue_median_ms={0}" -f $Summary.LatestBridgeMediaSendQueueEnqueueToQueueDequeueMedianMs),
        ("queue_enqueue_to_queue_dequeue_p95_ms={0}" -f $Summary.LatestBridgeMediaSendQueueEnqueueToQueueDequeueP95Ms),
        ("queue_enqueue_to_queue_dequeue_max_ms={0}" -f $Summary.LatestBridgeMediaSendQueueEnqueueToQueueDequeueMaxMs),
        ("queue_dequeue_to_media_send_started_avg_ms={0}" -f $Summary.LatestBridgeMediaSendQueueDequeueToMediaSendStartedAvgMs),
        ("queue_dequeue_to_media_send_started_median_ms={0}" -f $Summary.LatestBridgeMediaSendQueueDequeueToMediaSendStartedMedianMs),
        ("queue_dequeue_to_media_send_started_p95_ms={0}" -f $Summary.LatestBridgeMediaSendQueueDequeueToMediaSendStartedP95Ms),
        ("queue_dequeue_to_media_send_started_max_ms={0}" -f $Summary.LatestBridgeMediaSendQueueDequeueToMediaSendStartedMaxMs),
        ("media_send_started_to_media_send_resolved_avg_ms={0}" -f $Summary.LatestBridgeMediaSendMediaSendStartedToMediaSendResolvedAvgMs),
        ("media_send_started_to_media_send_resolved_median_ms={0}" -f $Summary.LatestBridgeMediaSendMediaSendStartedToMediaSendResolvedMedianMs),
        ("media_send_started_to_media_send_resolved_p95_ms={0}" -f $Summary.LatestBridgeMediaSendMediaSendStartedToMediaSendResolvedP95Ms),
        ("media_send_started_to_media_send_resolved_max_ms={0}" -f $Summary.LatestBridgeMediaSendMediaSendStartedToMediaSendResolvedMaxMs),
        ("frames_sent={0}" -f $Summary.LatestBridgeMediaSendFramesSent),
        ("send_failures={0}" -f $Summary.LatestBridgeMediaSendFailures),
        ("queue_drops={0}" -f $Summary.LatestBridgeMediaSendQueueDrops),
        ("queue_mode={0}" -f $Summary.LatestBridgeMediaSendQueueMode),
        ("queue_depth={0}" -f $Summary.LatestBridgeMediaSendQueueDepth),
        ("oldest_queued_age_ms={0}" -f $Summary.LatestBridgeMediaSendOldestQueuedAgeMs),
        ("sample_window_ms={0}" -f $Summary.LatestBridgeMediaSendSampleWindowMs),
        '',
        'bridge_media_send_summary_lines:'
    ) + @($Summary.BridgeMediaSendSummaryLines)

    $bridgeTransportHealthSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("selected_rpc={0}" -f $Summary.LatestBridgeTransportHealthSelectedRpc),
        ("selected_rpc_key={0}" -f $Summary.LatestBridgeTransportHealthSelectedRpcKey),
        ("selected_rpc_stage={0}" -f $Summary.LatestBridgeTransportHealthSelectedRpcStage),
        ("connect_id={0}" -f $Summary.LatestBridgeTransportHealthConnectId),
        ("connect_key={0}" -f $Summary.LatestBridgeTransportHealthConnectKey),
        ("ready_emitted={0}" -f $Summary.LatestBridgeTransportHealthReadyEmitted),
        ("client_ready_age_ms={0}" -f $Summary.LatestBridgeTransportHealthClientReadyAgeMs),
        ("disconnect_count_since_last={0}" -f $Summary.LatestBridgeTransportHealthDisconnectCountSinceLast),
        ("connect_failed_count_since_last={0}" -f $Summary.LatestBridgeTransportHealthConnectFailedCountSinceLast),
        ("ws_error_count_since_last={0}" -f $Summary.LatestBridgeTransportHealthWsErrorCountSinceLast),
        ("rpc_fallback_attempt_count_since_last={0}" -f $Summary.LatestBridgeTransportHealthRpcFallbackAttemptCountSinceLast),
        ("control_ready={0}" -f $Summary.LatestBridgeTransportHealthControlReady),
        ("media_ready={0}" -f $Summary.LatestBridgeTransportHealthMediaReady),
        ("bulk_ready={0}" -f $Summary.LatestBridgeTransportHealthBulkReady),
        ("frames_sent_since_last={0}" -f $Summary.LatestBridgeTransportHealthFramesSentSinceLast),
        ("latest_disconnect_reason={0}" -f $Summary.LatestBridgeTransportHealthLatestDisconnectReason),
        ("control_subclients={0}" -f $Summary.LatestBridgeTransportHealthControlSubClients),
        ("media_subclients={0}" -f $Summary.LatestBridgeTransportHealthMediaSubClients),
        ("bulk_subclients={0}" -f $Summary.LatestBridgeTransportHealthBulkSubClients),
        ("external_topology_profile={0}" -f $(if ([string]::IsNullOrWhiteSpace($env:NLINK_SCREENSHARE_EXTERNAL_TOPOLOGY_PROFILE)) { 'Default' } else { $env:NLINK_SCREENSHARE_EXTERNAL_TOPOLOGY_PROFILE })),
        ("sample_window_ms={0}" -f $Summary.LatestBridgeTransportHealthSampleWindowMs),
        ("unique_selected_rpc_count={0}" -f $Summary.LatestBridgeTransportHealthUniqueSelectedRpcCount),
        '',
        'bridge_transport_health_summary_lines:'
    ) + @($Summary.BridgeTransportHealthSummaryLines)

    $helperEpochLossSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("worst_epoch_by_visible_apply_ratio={0}" -f $Summary.WorstEpochByVisibleApplyRatio),
        ("worst_epoch_visible_apply_ratio={0}" -f $Summary.WorstEpochVisibleApplyRatio),
        ("applied_head_frame_id={0}" -f $Summary.LatestHelperAppliedHeadFrameId),
        ("ordered_emit_head_frame_id={0}" -f $Summary.LatestHelperOrderedEmitHeadFrameId),
        ("winning_recovery_frame_id={0}" -f $Summary.LatestHelperWinningRecoveryFrameId),
        ("recovery_owner_replaced_count={0}" -f $Summary.LatestHelperRecoveryOwnerReplacedCount),
        ("late_fragment_after_applied_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterAppliedHeadCount),
        ("late_fragment_after_ordered_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterOrderedHeadCount),
        '',
        'helper_epoch_loss_lines:'
    ) + @($Summary.HelperEpochLossLines)

    $promotionSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("promotion_blocker_rate_gate_ticks={0}" -f $Summary.LatestPromotionBlockerRateGateTicks),
        ("promotion_blocker_helper_pressure_ticks={0}" -f $Summary.LatestPromotionBlockerHelperPressureTicks),
        ("promotion_blocker_helper_warmup_ticks={0}" -f $Summary.LatestPromotionBlockerHelperWarmupTicks),
        ("promotion_blocker_helper_apply_count_ticks={0}" -f $Summary.LatestPromotionBlockerHelperApplyCountTicks),
        ("promotion_blocker_bridge_health_ticks={0}" -f $Summary.LatestPromotionBlockerBridgeHealthTicks),
        ("promotion_blocker_recovery_lock_ticks={0}" -f $Summary.LatestPromotionBlockerRecoveryLockTicks),
        ("promotion_blocker_queue_evict_ticks={0}" -f $Summary.LatestPromotionBlockerQueueEvictTicks),
        ("promotion_blocker_capture_age_ticks={0}" -f $Summary.LatestPromotionBlockerCaptureAgeTicks),
        ("promotion_blocker_encode_budget_ticks={0}" -f $Summary.LatestPromotionBlockerEncodeBudgetTicks),
        ("promotion_blocker_transition_grace_ticks={0}" -f $Summary.LatestPromotionBlockerTransitionGraceTicks),
        ("promotion_encode_soft_spike_count={0}" -f $Summary.LatestPromotionEncodeSoftSpikeCount),
        ("promotion_encode_soft_spike_reset_suppressed_count={0}" -f $Summary.LatestPromotionEncodeSoftSpikeResetSuppressedCount),
        ("blocked_by_missing_helper_proof={0}" -f $Summary.PromotionBlockedByMissingHelperProofCount),
        ("blocked_by_stale_helper_proof={0}" -f $Summary.PromotionBlockedByStaleHelperProofCount),
        ("blocked_by_encode_budget={0}" -f $Summary.PromotionBlockedByEncodeBudgetCount),
        ("blocked_by_encode_budget_alone={0}" -f $Summary.PromotionBlockedByEncodeBudgetAloneCount),
        ("helper_visible_head_runtime_sender_mismatch={0}" -f $Summary.HelperVisibleHeadRuntimeSenderMismatch),
        ("healthy_tick_reset_reason_counts={0}" -f $(if ([string]::IsNullOrWhiteSpace($Summary.LatestHealthyTickResetReasonCounts)) { '(none)' } else { $Summary.LatestHealthyTickResetReasonCounts })),
        ("recent_entries={0}" -f $(if ([string]::IsNullOrWhiteSpace($Summary.LatestReducedPromotionRecentEntries)) { '(none)' } else { $Summary.LatestReducedPromotionRecentEntries })),
        '',
        'promotion_summary_lines:'
    ) + @($Summary.ReducedPromotionSummaryLines)

    $senderCadenceSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("frames_queued={0}" -f $Summary.LatestFramesQueued),
        ("frames_deferred_to_send_slot={0}" -f $Summary.LatestFramesDeferredToSendSlot),
        ("frames_replaced_before_send_slot={0}" -f $Summary.LatestFramesReplacedBeforeSendSlot),
        ("frames_dropped_by_queue_evict={0}" -f $Summary.LatestFramesDroppedByQueueEvict),
        ("protected_recovery_frames_dispatched_count={0}" -f $Summary.LatestProtectedRecoveryFramesDispatchedCount),
        ("recovery_protected_frame_blocked_by_ordinary_count={0}" -f $Summary.LatestRecoveryProtectedFrameBlockedByOrdinaryCount),
        ("ordinary_sender_slot_replace_count={0}" -f $Summary.LatestFramesReplacedBeforeSendSlot),
        ("ordinary_sender_queue_evict_count={0}" -f $Summary.LatestFramesDroppedByQueueEvict),
        ("send_slot_empty_count={0}" -f $Summary.LatestSendSlotEmptyCount),
        ("slot_coalescing_active={0}" -f $Summary.LatestSlotCoalescingActive),
        ("raw_frames_deferred_to_encode_slot={0}" -f $Summary.LatestRawFramesDeferredToEncodeSlot),
        ("raw_frames_replaced_before_encode_slot={0}" -f $Summary.LatestRawFramesReplacedBeforeEncodeSlot),
        ("raw_encode_slot_empty_count={0}" -f $Summary.LatestRawEncodeSlotEmptyCount),
        ("raw_slot_coalescing_active={0}" -f $Summary.LatestRawSlotCoalescingActive),
        ("source_superseded_pending_frames={0}" -f $Summary.LatestSourceSupersededPendingFrames),
        ("helper_decoded_apply_queue_overflow_count={0}" -f $Summary.LatestHelperDecodedApplyQueueOverflowCount),
        ("ordinary_raw_loss_count={0}" -f $Summary.LatestOrdinaryRawLossCount),
        ("ordinary_sender_loss_count={0}" -f $Summary.LatestOrdinarySenderLossCount),
        ("ordinary_helper_loss_count={0}" -f $Summary.LatestOrdinaryHelperLossCount),
        ("dominant_ordinary_freshness_loss_boundary={0}" -f $Summary.DominantOrdinaryFreshnessLossBoundary),
        ("promotion_capture_to_send_budget_ms={0}" -f $Summary.LatestPromotionCaptureToSendBudgetMs),
        ("promotion_blocker_rate_gate_ticks={0}" -f $Summary.LatestPromotionBlockerRateGateTicks),
        ("promotion_blocker_helper_pressure_ticks={0}" -f $Summary.LatestPromotionBlockerHelperPressureTicks),
        ("recovery_burst_active={0}" -f $Summary.LatestRecoveryBurstActive),
        ("recovery_burst_phase={0}" -f $Summary.LatestRecoveryBurstPhase),
        ("recovery_burst_stream_epoch={0}" -f $Summary.LatestRecoveryBurstStreamEpoch),
        ("recovery_owner_frame_id={0}" -f $Summary.LatestRecoveryOwnerFrameId),
        ("recovery_protected_follower_count={0}" -f $Summary.LatestRecoveryProtectedFollowerCount),
        ("recovery_gap_count={0}" -f $Summary.LatestRecoveryGapCount),
        ("recovery_gap_to_keyframe_request_ms={0}" -f $Summary.LatestRecoveryGapToKeyframeRequestMs),
        ("recovery_keyframe_request_to_owner_emit_ms={0}" -f $Summary.LatestRecoveryKeyframeRequestToOwnerEmitMs),
        ("recovery_owner_ack_window_ms={0}" -f $Summary.LatestRecoveryOwnerAckWindowMs),
        ("recovery_owner_emit_to_ack_ms={0}" -f $Summary.LatestRecoveryOwnerEmitToAckMs),
        ("recovery_post_ack_hold_active={0}" -f $Summary.LatestRecoveryPostAckHoldActive),
        ("recovery_post_ack_hold_started_count={0}" -f $Summary.LatestRecoveryPostAckHoldStartedCount),
        ("recovery_post_ack_hold_expired_count={0}" -f $Summary.LatestRecoveryPostAckHoldExpiredCount),
        ("recovery_post_ack_hold_suppressed_reopen_count={0}" -f $Summary.LatestRecoveryPostAckHoldSuppressedReopenCount),
        ("recovery_owner_ack_frame_id={0}" -f $Summary.LatestRecoveryOwnerAckFrameId),
        ("recovery_ack_source={0}" -f $Summary.LatestRecoveryAckSource),
        ("recovery_owner_emit_to_first_visible_apply_ms={0}" -f $Summary.LatestRecoveryOwnerEmitToFirstVisibleApplyMs),
        ("recovery_burst_control_fallback_count={0}" -f $Summary.LatestRecoveryBurstControlFallbackCount),
        ("recovery_burst_timeout_count={0}" -f $Summary.LatestRecoveryBurstTimeoutCount),
        ("recovery_burst_completed_count={0}" -f $Summary.LatestRecoveryBurstCompletedCount),
        ("recovery_burst_restart_suppressed_count={0}" -f $Summary.LatestRecoveryBurstRestartSuppressedCount),
        ("recovery_burst_encoder_rerequest_count={0}" -f $Summary.LatestRecoveryBurstEncoderRerequestCount),
        ("recovery_owner_pending_forced_reset_count={0}" -f $Summary.LatestRecoveryOwnerPendingForcedResetCount),
        ("recovery_keyframe_emitted_after_forced_reset_count={0}" -f $Summary.LatestRecoveryKeyframeEmittedAfterForcedResetCount),
        ("recovery_burst_completed_by_helper_ack_count={0}" -f $Summary.LatestRecoveryBurstCompletedByHelperAckCount),
        ("recovery_burst_completed_by_applied_head_ack_count={0}" -f $Summary.LatestRecoveryBurstCompletedByAppliedHeadAckCount),
        ("recovery_burst_completed_by_last_visible_apply_ack_count={0}" -f $Summary.LatestRecoveryBurstCompletedByLastVisibleApplyAckCount),
        ("recovery_burst_completed_by_visible_recovery_floor_count={0}" -f $Summary.LatestRecoveryBurstCompletedByVisibleRecoveryFloorCount),
        ("recovery_burst_completed_by_visible_apply_fallback_count={0}" -f $Summary.LatestRecoveryBurstCompletedByVisibleApplyFallbackCount),
        ("recovery_burst_completed_by_timeout_count={0}" -f $Summary.LatestRecoveryBurstCompletedByTimeoutCount),
        ("recovery_burst_completed_by_protected_frames_count={0}" -f $Summary.LatestRecoveryBurstCompletedByProtectedFramesCount),
        ("recovery_burst_profile_transition_deferred_count={0}" -f $Summary.LatestRecoveryBurstProfileTransitionDeferredCount),
        ("recovery_burst_profile_transition_takeover_count={0}" -f $Summary.LatestRecoveryBurstProfileTransitionTakeoverCount),
        ("recovery_burst_stale_request_suppressed_count={0}" -f $Summary.LatestRecoveryBurstStaleRequestSuppressedCount),
        ("recovery_burst_request_suppressed_due_to_helper_ack_count={0}" -f $Summary.LatestRecoveryBurstRequestSuppressedDueToHelperAckCount),
        ("recovery_burst_started_while_helper_proof_healthy_count={0}" -f $Summary.LatestRecoveryBurstStartedWhileHelperProofHealthyCount),
        ("helper_progress_past_owner_without_burst_ack_count={0}" -f $Summary.LatestHelperProgressPastOwnerWithoutBurstAckCount),
        ("post_recovery_age_grace_active={0}" -f $Summary.LatestPostRecoveryAgeGraceActive),
        ("post_recovery_age_grace_suppressed_count={0}" -f $Summary.LatestPostRecoveryAgeGraceSuppressedCount),
        ("last_completed_recovery_epoch={0}" -f $Summary.LatestLastCompletedRecoveryEpoch),
        ("last_completed_recovery_owner_frame_id={0}" -f $Summary.LatestLastCompletedRecoveryOwnerFrameId),
        ("last_completed_recovery_ack_frame_id={0}" -f $Summary.LatestLastCompletedRecoveryAckFrameId),
        ("last_completed_recovery_ack_source={0}" -f $Summary.LatestLastCompletedRecoveryAckSource),
        ("last_completed_recovery_owner_emit_to_ack_ms={0}" -f $Summary.LatestLastCompletedRecoveryOwnerEmitToAckMs),
        ("last_completed_recovery_completion_kind={0}" -f $Summary.LatestLastCompletedRecoveryCompletionKind),
        ("recovery_completion_accounting_mismatch={0}" -f $Summary.LatestRecoveryCompletionAccountingMismatch),
        ("recovery_owner_pending_non_key_held_count={0}" -f $Summary.LatestRecoveryOwnerPendingNonKeyHeldCount),
        ("recovery_owner_pending_non_key_replaced_count={0}" -f $Summary.LatestRecoveryOwnerPendingNonKeyReplacedCount),
        ("recovery_owner_unacked_non_key_held_count={0}" -f $Summary.LatestRecoveryOwnerUnackedNonKeyHeldCount),
        ("recovery_owner_unacked_non_key_replaced_count={0}" -f $Summary.LatestRecoveryOwnerUnackedNonKeyReplacedCount),
        ("recovery_same_epoch_keyframe_suppressed_while_owner_unacked_count={0}" -f $Summary.LatestRecoverySameEpochKeyframeSuppressedWhileOwnerUnackedCount),
        ("recovery_owner_replaced_before_ack_count={0}" -f $Summary.LatestRecoveryOwnerReplacedBeforeAckCount),
        ("high_frame_age_suppressed_during_owner_ack_count={0}" -f $Summary.LatestHighFrameAgeSuppressedDuringOwnerAckCount),
        ("helper_progress_fact_bypass_send_count={0}" -f $Summary.LatestHelperPressureSendBypassedForVisibleProgressCount),
        ("helper_proof_keepalive_send_count={0}" -f $Summary.LatestHelperProofKeepaliveSendCount),
        ("helper_proof_keepalive_timer_driven_send_count={0}" -f $Summary.LatestHelperProofKeepaliveTimerDrivenSendCount),
        ("helper_proof_keepalive_last_head_frame_id={0}" -f $Summary.LatestHelperProofKeepaliveLastHeadFrameId),
        ("helper_proof_keepalive_last_send_age_ms={0}" -f $Summary.LatestHelperProofKeepaliveLastSendAgeMs),
        ("remote_helper_fact_healthy_active={0}" -f $Summary.LatestRemoteHelperFactHealthyActive),
        ("remote_helper_fact_healthy_source={0}" -f $Summary.LatestRemoteHelperFactHealthySource),
        ("remote_helper_fact_proof_frame_id={0}" -f $Summary.LatestRemoteHelperFactProofFrameId),
        ("remote_helper_fact_last_message_age_ms={0}" -f $Summary.LatestRemoteHelperFactLastMessageAgeMs),
        ("remote_helper_fact_healthy_clear_count={0}" -f $Summary.LatestRemoteHelperFactHealthyClearCount),
        ("remote_helper_fact_healthy_clear_reason={0}" -f $Summary.LatestRemoteHelperFactHealthyClearReason),
        ("helper_first_visible_apply_to_sender_fact_send_ms={0}" -f $Summary.LatestHelperFirstVisibleApplyToSenderFactSendMs),
        ("sender_received_helper_progress_during_continuity_loss_count={0}" -f $Summary.LatestSenderReceivedHelperProgressDuringContinuityLossCount),
        ("recovery_timeout_while_helper_head_advanced_count={0}" -f $Summary.LatestRecoveryTimeoutWhileHelperHeadAdvancedCount),
        ("helper_ack_after_fact_send_ms={0}" -f $Summary.LatestHelperAckAfterFactSendMs),
        ("post_ack_mode_grace_suppressed_high_frame_age_count={0}" -f $Summary.LatestPostAckModeGraceSuppressedHighFrameAgeCount),
        ("bootstrap_grace_suppressed_catch_up_count={0}" -f $Summary.LatestBootstrapGraceSuppressedCatchUpCount),
        ("catch_up_recovery_suppressed_due_to_remote_high_frame_age_count={0}" -f $Summary.LatestCatchUpRecoverySuppressedDueToRemoteHighFrameAgeCount),
        ("catch_up_exit_while_remote_high_frame_age_pressure_count={0}" -f $Summary.LatestCatchUpExitWhileRemoteHighFrameAgePressureCount),
        ("last_acknowledged_recovery_owner_frame_id={0}" -f $Summary.LatestLastAcknowledgedRecoveryOwnerFrameId),
        ("last_acknowledged_helper_head_frame_id={0}" -f $Summary.LatestLastAcknowledgedHelperHeadFrameId),
        ("remote_helper_visible_head_frame_id={0}" -f $Summary.LatestRemoteHelperVisibleHeadFrameId),
        ("remote_helper_visible_recovery_floor_frame_id={0}" -f $Summary.LatestRemoteHelperVisibleRecoveryFloorFrameId),
        ("remote_helper_current_epoch_recovery_keyframe_apply_count={0}" -f $Summary.LatestRemoteHelperCurrentEpochRecoveryKeyframeApplyCount),
        ("last_acknowledged_visible_helper_head_frame_id={0}" -f $Summary.LatestLastAcknowledgedVisibleHelperHeadFrameId),
        ("last_acknowledged_helper_proof_age_ms={0}" -f $Summary.LatestLastAcknowledgedHelperProofAgeMs),
        ("persisted_release_floor_epoch={0}" -f $Summary.LatestPersistedReleaseFloorEpoch),
        ("satisfied_recovery_floor_frame_id={0}" -f $Summary.LatestSatisfiedRecoveryFloorFrameId),
        ("satisfied_recovery_floor_source={0}" -f $Summary.LatestSatisfiedRecoveryFloorSource),
        ("satisfied_recovery_floor_visible_proof_count={0}" -f $Summary.LatestSatisfiedRecoveryFloorVisibleProofCount),
        ("continuity_signal_ignored_due_to_satisfied_floor_count={0}" -f $Summary.LatestContinuitySignalIgnoredDueToSatisfiedFloorCount),
        ("continuity_signal_ignored_due_to_visible_satisfied_floor_count={0}" -f $Summary.LatestContinuitySignalIgnoredDueToVisibleSatisfiedFloorCount),
        ("recovery_lock_cleared_by_acknowledged_proof_count={0}" -f $Summary.LatestRecoveryLockClearedByAcknowledgedProofCount),
        ("recovery_lock_cleared_by_visible_proof_count={0}" -f $Summary.LatestRecoveryLockClearedByVisibleProofCount),
        ("recovery_lock_last_clear_reason={0}" -f $Summary.LatestRecoveryLockLastClearReason),
        ("recovery_control_bootstrap_retry_skipped_due_to_burst_resolved_count={0}" -f $Summary.RecoveryControlBootstrapRetrySkippedDueToBurstResolvedCount),
        ("recovery_control_bootstrap_retry_queued_after_burst_resolution_count={0}" -f $Summary.RecoveryControlBootstrapRetryQueuedAfterBurstResolutionCount),
        ("recovery_burst_completed_without_helper_advance={0}" -f $Summary.RecoveryBurstCompletedWithoutHelperAdvance),
        ("recovery_ack_missed_despite_helper_progress={0}" -f $Summary.RecoveryAckMissedDespiteHelperProgress)
    )

    $transportModeSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("effective_media_plane_active={0}" -f $Summary.EffectiveMediaPlaneActive),
        ("recovery_used_control_fallback={0}" -f $Summary.RecoveryUsedControlFallback),
        ("steady_state_used_control_fallback={0}" -f $Summary.SteadyStateUsedControlFallback),
        ("bridge_media_messages_received={0}" -f $Summary.LatestBridgeMediaMessagesReceived),
        ("media_plane_frames_sent={0}" -f $Summary.LatestMediaPlaneFramesSent),
        ("media_plane_attached={0}" -f $Summary.LatestMediaPlaneAttached),
        ("recovery_control_fallback_queued_count={0}" -f $Summary.RecoveryControlFallbackQueuedCount),
        ("steady_state_control_fallback_queued_count={0}" -f $Summary.SteadyStateControlFallbackQueuedCount),
        ("avg_fragments_per_frame={0}" -f $Summary.LatestAvgFragmentsPerFrame),
        ("avg_transport_payloads_per_frame={0}" -f $Summary.LatestAvgPayloadsPerFrame),
        ("batched_payloads_sent={0}" -f $Summary.LatestBatchPayloadCount),
        ("legacy_fragment_payloads_sent={0}" -f $Summary.LatestLegacyPayloadCount),
        ("ordinary_non_key_batched_payloads_sent={0}" -f $Summary.LatestOrdinaryNonKeyBatchedPayloadCount),
        ("ordinary_non_key_legacy_payloads_sent={0}" -f $Summary.LatestOrdinaryNonKeyLegacyPayloadCount),
        ("keyframe_recovery_batched_payloads_sent={0}" -f $Summary.LatestKeyframeRecoveryBatchedPayloadCount)
    )

    $recoveryBurstSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("recovery_burst_active={0}" -f $Summary.LatestRecoveryBurstActive),
        ("recovery_burst_phase={0}" -f $Summary.LatestRecoveryBurstPhase),
        ("recovery_burst_stream_epoch={0}" -f $Summary.LatestRecoveryBurstStreamEpoch),
        ("recovery_owner_frame_id={0}" -f $Summary.LatestRecoveryOwnerFrameId),
        ("recovery_protected_follower_count={0}" -f $Summary.LatestRecoveryProtectedFollowerCount),
        ("recovery_gap_count={0}" -f $Summary.LatestRecoveryGapCount),
        ("recovery_gap_to_keyframe_request_ms={0}" -f $Summary.LatestRecoveryGapToKeyframeRequestMs),
        ("recovery_keyframe_request_to_owner_emit_ms={0}" -f $Summary.LatestRecoveryKeyframeRequestToOwnerEmitMs),
        ("recovery_owner_ack_window_ms={0}" -f $Summary.LatestRecoveryOwnerAckWindowMs),
        ("recovery_owner_emit_to_ack_ms={0}" -f $Summary.LatestRecoveryOwnerEmitToAckMs),
        ("recovery_post_ack_hold_active={0}" -f $Summary.LatestRecoveryPostAckHoldActive),
        ("recovery_post_ack_hold_started_count={0}" -f $Summary.LatestRecoveryPostAckHoldStartedCount),
        ("recovery_post_ack_hold_expired_count={0}" -f $Summary.LatestRecoveryPostAckHoldExpiredCount),
        ("recovery_post_ack_hold_suppressed_reopen_count={0}" -f $Summary.LatestRecoveryPostAckHoldSuppressedReopenCount),
        ("recovery_owner_ack_frame_id={0}" -f $Summary.LatestRecoveryOwnerAckFrameId),
        ("recovery_ack_source={0}" -f $Summary.LatestRecoveryAckSource),
        ("recovery_owner_emit_to_first_visible_apply_ms={0}" -f $Summary.LatestRecoveryOwnerEmitToFirstVisibleApplyMs),
        ("recovery_burst_control_fallback_count={0}" -f $Summary.LatestRecoveryBurstControlFallbackCount),
        ("recovery_burst_timeout_count={0}" -f $Summary.LatestRecoveryBurstTimeoutCount),
        ("recovery_burst_completed_count={0}" -f $Summary.LatestRecoveryBurstCompletedCount),
        ("recovery_burst_restart_suppressed_count={0}" -f $Summary.LatestRecoveryBurstRestartSuppressedCount),
        ("recovery_burst_encoder_rerequest_count={0}" -f $Summary.LatestRecoveryBurstEncoderRerequestCount),
        ("recovery_owner_pending_forced_reset_count={0}" -f $Summary.LatestRecoveryOwnerPendingForcedResetCount),
        ("recovery_keyframe_emitted_after_forced_reset_count={0}" -f $Summary.LatestRecoveryKeyframeEmittedAfterForcedResetCount),
        ("recovery_burst_completed_by_helper_ack_count={0}" -f $Summary.LatestRecoveryBurstCompletedByHelperAckCount),
        ("recovery_burst_completed_by_applied_head_ack_count={0}" -f $Summary.LatestRecoveryBurstCompletedByAppliedHeadAckCount),
        ("recovery_burst_completed_by_last_visible_apply_ack_count={0}" -f $Summary.LatestRecoveryBurstCompletedByLastVisibleApplyAckCount),
        ("recovery_burst_completed_by_visible_recovery_floor_count={0}" -f $Summary.LatestRecoveryBurstCompletedByVisibleRecoveryFloorCount),
        ("recovery_burst_completed_by_visible_apply_fallback_count={0}" -f $Summary.LatestRecoveryBurstCompletedByVisibleApplyFallbackCount),
        ("recovery_burst_completed_by_timeout_count={0}" -f $Summary.LatestRecoveryBurstCompletedByTimeoutCount),
        ("recovery_burst_completed_by_protected_frames_count={0}" -f $Summary.LatestRecoveryBurstCompletedByProtectedFramesCount),
        ("recovery_burst_profile_transition_deferred_count={0}" -f $Summary.LatestRecoveryBurstProfileTransitionDeferredCount),
        ("recovery_burst_profile_transition_takeover_count={0}" -f $Summary.LatestRecoveryBurstProfileTransitionTakeoverCount),
        ("recovery_burst_stale_request_suppressed_count={0}" -f $Summary.LatestRecoveryBurstStaleRequestSuppressedCount),
        ("recovery_burst_request_suppressed_due_to_helper_ack_count={0}" -f $Summary.LatestRecoveryBurstRequestSuppressedDueToHelperAckCount),
        ("recovery_burst_started_while_helper_proof_healthy_count={0}" -f $Summary.LatestRecoveryBurstStartedWhileHelperProofHealthyCount),
        ("helper_progress_past_owner_without_burst_ack_count={0}" -f $Summary.LatestHelperProgressPastOwnerWithoutBurstAckCount),
        ("post_recovery_age_grace_active={0}" -f $Summary.LatestPostRecoveryAgeGraceActive),
        ("post_recovery_age_grace_suppressed_count={0}" -f $Summary.LatestPostRecoveryAgeGraceSuppressedCount),
        ("last_completed_recovery_epoch={0}" -f $Summary.LatestLastCompletedRecoveryEpoch),
        ("last_completed_recovery_owner_frame_id={0}" -f $Summary.LatestLastCompletedRecoveryOwnerFrameId),
        ("last_completed_recovery_ack_frame_id={0}" -f $Summary.LatestLastCompletedRecoveryAckFrameId),
        ("last_completed_recovery_ack_source={0}" -f $Summary.LatestLastCompletedRecoveryAckSource),
        ("last_completed_recovery_owner_emit_to_ack_ms={0}" -f $Summary.LatestLastCompletedRecoveryOwnerEmitToAckMs),
        ("last_completed_recovery_completion_kind={0}" -f $Summary.LatestLastCompletedRecoveryCompletionKind),
        ("recovery_completion_accounting_mismatch={0}" -f $Summary.LatestRecoveryCompletionAccountingMismatch),
        ("recovery_owner_pending_non_key_held_count={0}" -f $Summary.LatestRecoveryOwnerPendingNonKeyHeldCount),
        ("recovery_owner_pending_non_key_replaced_count={0}" -f $Summary.LatestRecoveryOwnerPendingNonKeyReplacedCount),
        ("recovery_owner_unacked_non_key_held_count={0}" -f $Summary.LatestRecoveryOwnerUnackedNonKeyHeldCount),
        ("recovery_owner_unacked_non_key_replaced_count={0}" -f $Summary.LatestRecoveryOwnerUnackedNonKeyReplacedCount),
        ("recovery_same_epoch_keyframe_suppressed_while_owner_unacked_count={0}" -f $Summary.LatestRecoverySameEpochKeyframeSuppressedWhileOwnerUnackedCount),
        ("recovery_owner_replaced_before_ack_count={0}" -f $Summary.LatestRecoveryOwnerReplacedBeforeAckCount),
        ("high_frame_age_suppressed_during_owner_ack_count={0}" -f $Summary.LatestHighFrameAgeSuppressedDuringOwnerAckCount),
        ("helper_progress_fact_bypass_send_count={0}" -f $Summary.LatestHelperPressureSendBypassedForVisibleProgressCount),
        ("helper_proof_keepalive_send_count={0}" -f $Summary.LatestHelperProofKeepaliveSendCount),
        ("helper_proof_keepalive_timer_driven_send_count={0}" -f $Summary.LatestHelperProofKeepaliveTimerDrivenSendCount),
        ("helper_proof_keepalive_last_head_frame_id={0}" -f $Summary.LatestHelperProofKeepaliveLastHeadFrameId),
        ("helper_proof_keepalive_last_send_age_ms={0}" -f $Summary.LatestHelperProofKeepaliveLastSendAgeMs),
        ("remote_helper_fact_healthy_active={0}" -f $Summary.LatestRemoteHelperFactHealthyActive),
        ("remote_helper_fact_healthy_source={0}" -f $Summary.LatestRemoteHelperFactHealthySource),
        ("remote_helper_fact_proof_frame_id={0}" -f $Summary.LatestRemoteHelperFactProofFrameId),
        ("remote_helper_fact_last_message_age_ms={0}" -f $Summary.LatestRemoteHelperFactLastMessageAgeMs),
        ("remote_helper_fact_healthy_clear_count={0}" -f $Summary.LatestRemoteHelperFactHealthyClearCount),
        ("remote_helper_fact_healthy_clear_reason={0}" -f $Summary.LatestRemoteHelperFactHealthyClearReason),
        ("helper_first_visible_apply_to_sender_fact_send_ms={0}" -f $Summary.LatestHelperFirstVisibleApplyToSenderFactSendMs),
        ("sender_received_helper_progress_during_continuity_loss_count={0}" -f $Summary.LatestSenderReceivedHelperProgressDuringContinuityLossCount),
        ("helper_ack_after_fact_send_ms={0}" -f $Summary.LatestHelperAckAfterFactSendMs),
        ("last_acknowledged_recovery_owner_frame_id={0}" -f $Summary.LatestLastAcknowledgedRecoveryOwnerFrameId),
        ("last_acknowledged_helper_head_frame_id={0}" -f $Summary.LatestLastAcknowledgedHelperHeadFrameId),
        ("remote_helper_visible_head_frame_id={0}" -f $Summary.LatestRemoteHelperVisibleHeadFrameId),
        ("remote_helper_visible_recovery_floor_frame_id={0}" -f $Summary.LatestRemoteHelperVisibleRecoveryFloorFrameId),
        ("remote_helper_current_epoch_recovery_keyframe_apply_count={0}" -f $Summary.LatestRemoteHelperCurrentEpochRecoveryKeyframeApplyCount),
        ("last_acknowledged_visible_helper_head_frame_id={0}" -f $Summary.LatestLastAcknowledgedVisibleHelperHeadFrameId),
        ("last_acknowledged_helper_proof_age_ms={0}" -f $Summary.LatestLastAcknowledgedHelperProofAgeMs),
        ("persisted_release_floor_epoch={0}" -f $Summary.LatestPersistedReleaseFloorEpoch),
        ("satisfied_recovery_floor_frame_id={0}" -f $Summary.LatestSatisfiedRecoveryFloorFrameId),
        ("satisfied_recovery_floor_source={0}" -f $Summary.LatestSatisfiedRecoveryFloorSource),
        ("satisfied_recovery_floor_visible_proof_count={0}" -f $Summary.LatestSatisfiedRecoveryFloorVisibleProofCount),
        ("continuity_signal_ignored_due_to_satisfied_floor_count={0}" -f $Summary.LatestContinuitySignalIgnoredDueToSatisfiedFloorCount),
        ("continuity_signal_ignored_due_to_visible_satisfied_floor_count={0}" -f $Summary.LatestContinuitySignalIgnoredDueToVisibleSatisfiedFloorCount),
        ("recovery_lock_cleared_by_acknowledged_proof_count={0}" -f $Summary.LatestRecoveryLockClearedByAcknowledgedProofCount),
        ("recovery_lock_cleared_by_visible_proof_count={0}" -f $Summary.LatestRecoveryLockClearedByVisibleProofCount),
        ("recovery_lock_last_clear_reason={0}" -f $Summary.LatestRecoveryLockLastClearReason),
        ("recovery_control_bootstrap_retry_skipped_due_to_burst_resolved_count={0}" -f $Summary.RecoveryControlBootstrapRetrySkippedDueToBurstResolvedCount),
        ("recovery_control_bootstrap_retry_queued_after_burst_resolution_count={0}" -f $Summary.RecoveryControlBootstrapRetryQueuedAfterBurstResolutionCount),
        ("recovery_burst_completed_without_helper_advance={0}" -f $Summary.RecoveryBurstCompletedWithoutHelperAdvance),
        ("recovery_ack_missed_despite_helper_progress={0}" -f $Summary.RecoveryAckMissedDespiteHelperProgress)
    )

    $helperEpochTimelineSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("worst_epoch_by_recovery_lock_time={0}" -f $Summary.WorstEpochByRecoveryLockTime),
        ("worst_epoch_recovery_lock_time_ms={0}" -f $Summary.WorstEpochRecoveryLockTimeMs),
        '',
        'helper_epoch_timeline_lines:'
    ) + @($Summary.HelperEpochTimelineLines)

    $helperReassemblerRootCauseSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("dominant_reassembler_root_cause={0}" -f $Summary.DominantReassemblerRootCause),
        ("late_fragment_after_applied_head_count={0}" -f $Summary.AggregateLateFragmentAfterAppliedHeadCount),
        ("late_fragment_after_ordered_head_count={0}" -f $Summary.AggregateLateFragmentAfterOrderedHeadCount),
        ("late_fragment_after_stable_visible_head_count={0}" -f $Summary.LatestHelperLateFragmentAfterStableVisibleHeadCount),
        ("winning_recovery_frame_id={0}" -f $Summary.LatestHelperWinningRecoveryFrameId),
        ("ordered_emit_head_frame_id={0}" -f $Summary.LatestHelperOrderedEmitHeadFrameId),
        ("recovery_owner_replaced_count={0}" -f $Summary.AggregateRecoveryOwnerReplacedCount),
        ("older_epoch_cleanup_after_epoch_advance_count={0}" -f $Summary.AggregateOlderEpochCleanupAfterEpochAdvanceCount),
        ("actionable_late_fragment_count={0}" -f $Summary.AggregateActionableLateFragmentCount),
        ("worst_epoch_by_visible_apply_ratio={0}" -f $Summary.WorstEpochByVisibleApplyRatio),
        ("worst_epoch_visible_apply_ratio={0}" -f $Summary.WorstEpochVisibleApplyRatio),
        '',
        'helper_reassembler_root_cause_summary_lines:'
    ) + @($Summary.HelperReassemblerRootCauseSummaryLines)

    $helperPressureSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("dominant_helper_pressure_blocker={0}" -f $Summary.DominantHelperPressureBlocker),
        ("baseline_established={0}" -f $Summary.LatestHelperBaselineEstablished),
        ("baseline_capture_to_render_ms={0}" -f $Summary.LatestHelperBaselineCaptureToRenderMs),
        ("age_excess_ms={0}" -f $Summary.LatestHelperAgeExcessMs),
        ("applied_head_frame_id={0}" -f $Summary.LatestHelperAppliedHeadFrameId),
        ("high_frame_age_suppressed_due_to_visible_progress_count={0}" -f $Summary.AggregateHighFrameAgeSuppressedDueToVisibleProgressCount),
        ("progress_stall_ms={0}" -f $Summary.LatestHelperProgressStallMs),
        ("baseline_reseed_in_progress={0}" -f $Summary.LatestHelperBaselineReseedInProgress),
        ("age_pressure_consecutive_count={0}" -f $Summary.LatestHelperAgePressureConsecutiveCount),
        ("cadence_pressure_consecutive_count={0}" -f $Summary.LatestHelperCadencePressureConsecutiveCount),
        ("post_recovery_age_grace_active={0}" -f $Summary.LatestPostRecoveryAgeGraceActive),
        ("post_recovery_age_grace_suppressed_count={0}" -f $Summary.LatestPostRecoveryAgeGraceSuppressedCount),
        ("catch_up_suppressed_due_to_progress_count={0}" -f $Summary.LatestHelperCatchUpSuppressedDueToProgressCount),
        ("baseline_frozen_due_to_stall_count={0}" -f $Summary.LatestHelperBaselineFrozenDueToStallCount),
        ("baseline_reseed_after_recovery_count={0}" -f $Summary.LatestHelperBaselineReseedAfterRecoveryCount),
        ("cadence_stall_window_count={0}" -f $Summary.LatestHelperCadenceStallWindowCount),
        ("cadence_stall_trigger_count={0}" -f $Summary.LatestHelperCadenceStallTriggerCount),
        ("steady_visible_progress_active={0}" -f $Summary.LatestHelperSteadyVisibleProgressActive),
        ("steady_visible_progress_activation_frame_id={0}" -f $Summary.LatestHelperSteadyVisibleProgressActivationFrameId),
        ("stable_visible_head_frame_id={0}" -f $Summary.LatestHelperStableVisibleHeadFrameId),
        ("last_sent_stable_visible_head_frame_id={0}" -f $Summary.LatestHelperLastSentStableVisibleHeadFrameId),
        ("helper_proof_keepalive_send_count={0}" -f $Summary.LatestHelperProofKeepaliveSendCount),
        ("helper_proof_keepalive_timer_driven_send_count={0}" -f $Summary.LatestHelperProofKeepaliveTimerDrivenSendCount),
        ("helper_proof_keepalive_last_head_frame_id={0}" -f $Summary.LatestHelperProofKeepaliveLastHeadFrameId),
        ("helper_proof_keepalive_last_send_age_ms={0}" -f $Summary.LatestHelperProofKeepaliveLastSendAgeMs),
        ("steady_visible_progress_cleared_count={0}" -f $Summary.LatestHelperSteadyVisibleProgressClearedCount),
        ("steady_visible_progress_cleared_reason={0}" -f $Summary.LatestHelperSteadyVisibleProgressClearedReason),
        ("post_recovery_high_frame_age_suppressed_ticks={0}" -f $Summary.AggregatePostRecoveryHighFrameAgeSuppressedTicks),
        ("high_frame_age_suppressed_due_to_head_advance_count={0}" -f $Summary.LatestHelperHighFrameAgeSuppressedDueToHeadAdvanceCount),
        ("actionable_high_frame_age_count={0}" -f $Summary.LatestHelperActionableHighFrameAgeCount),
        ("bridge_health_advisory_count={0}" -f $Summary.LatestHelperBridgeHealthAdvisoryCount),
        ("bridge_health_actionable_count={0}" -f $Summary.LatestHelperBridgeHealthActionableCount),
        ("bridge_health_quarantine_suppressed_count={0}" -f $Summary.LatestHelperBridgeHealthQuarantineSuppressedCount),
        ("bridge_health_became_actionable_without_queue_or_drop_count={0}" -f $Summary.LatestHelperBridgeHealthActionableWithoutQueueOrDropCount),
        ("worst_epoch_by_recovery_lock_time={0}" -f $Summary.WorstEpochByRecoveryLockTime),
        ("worst_epoch_recovery_lock_time_ms={0}" -f $Summary.WorstEpochRecoveryLockTimeMs),
        '',
        'helper_pressure_summary_lines:'
    ) + @($Summary.HelperPressureSummaryLines)

    $helperRecoveryInvestigationSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("session_id={0}" -f $Summary.LatestHelperSessionId),
        ("dominant_reassembler_root_cause={0}" -f $Summary.DominantReassemblerRootCause),
        ("recovery_owner_replaced_count={0}" -f $Summary.LatestHelperRecoveryOwnerReplacedCount),
        ("older_epoch_cleanup_after_epoch_advance_count={0}" -f $Summary.LatestHelperOlderEpochCleanupAfterEpochAdvanceCount),
        ("actionable_late_fragment_count={0}" -f $Summary.LatestHelperActionableLateFragmentCount),
        ("baseline_established={0}" -f $Summary.LatestHelperBaselineEstablished),
        ("visible_head_frame_id={0}" -f $Summary.LatestHelperVisibleHeadFrameId),
        ("stable_visible_head_frame_id={0}" -f $Summary.LatestHelperStableVisibleHeadFrameId),
        ("visible_recovery_floor_frame_id={0}" -f $Summary.LatestHelperVisibleRecoveryFloorFrameId),
        ("applied_head_frame_id={0}" -f $Summary.LatestHelperAppliedHeadFrameId),
        ("ordered_emit_head_frame_id={0}" -f $Summary.LatestHelperOrderedEmitHeadFrameId),
        ("winning_recovery_frame_id={0}" -f $Summary.LatestHelperWinningRecoveryFrameId),
        '',
        'helper_recovery_epoch_investigation_lines:'
    ) + @($Summary.HelperRecoveryEpochInvestigationLines) + @(
        '',
        'helper_reassembler_recovery_owner_transition_lines:'
    ) + @($Summary.HelperReassemblerRecoveryOwnerTransitionLines) + @(
        '',
        'helper_reassembler_actionable_late_fragment_lines:'
    ) + @($Summary.HelperReassemblerActionableLateFragmentLines) + @(
        '',
        'helper_reassembler_older_epoch_cleanup_lines:'
    ) + @($Summary.HelperReassemblerOlderEpochCleanupLines)

    $healthSnapshotSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("sender_operating_state={0}" -f $Summary.LatestHealthSenderOperatingState),
        ("sender_guard_state={0}" -f $Summary.LatestHealthSenderGuardState),
        ("helper_session_phase={0}" -f $Summary.LatestHealthHelperSessionPhase),
        ("helper_recovery_mechanism={0}" -f $Summary.LatestHealthHelperRecoveryMechanism),
        ("dominant_loss_class={0}" -f $Summary.LatestHealthDominantLossClass),
        ("dominant_pressure_blocker={0}" -f $Summary.LatestHealthDominantPressureBlocker),
        ("dominant_trouble_domain={0}" -f $Summary.LatestHealthDominantTroubleDomain),
        ("recovery_active={0}" -f $Summary.LatestHealthRecoveryActive),
        ("baseline_established={0}" -f $Summary.LatestHealthBaselineEstablished),
        ("steady_visible_progress_active={0}" -f $Summary.LatestHealthSteadyVisibleProgressActive),
        '',
        'health_snapshot_lines:'
    ) + @($Summary.HealthSnapshotLines)

    $qualityPresentationSummary = @(
        ("log_path={0}" -f $Summary.LogPath),
        ("active_encode_target_width={0}" -f $Summary.LatestActiveEncodeTargetWidth),
        ("active_encode_target_height={0}" -f $Summary.LatestActiveEncodeTargetHeight),
        ("active_encode_target_bitrate={0}" -f $Summary.LatestActiveEncodeTargetBitrate),
        ("active_encode_target_fps={0}" -f $Summary.LatestActiveEncodeTargetFps),
        ("encoder_profile={0}" -f $Summary.LatestEncoderProfile),
        ("sender_freshness_mode={0}" -f $Summary.LatestSenderFreshnessMode),
        ("sender_operating_state={0}" -f $Summary.LatestHealthSenderOperatingState),
        ("sender_guard_state={0}" -f $Summary.LatestHealthSenderGuardState),
        ("effective_quality_preset={0}" -f $Summary.LatestEffectiveQualityPreset),
        ("capture_scale={0}" -f $Summary.LatestCaptureScale),
        ("last_encode_duration_ms={0}" -f $Summary.LatestLastEncodeDurationMs),
        ("last_preprocess_duration_ms={0}" -f $Summary.LatestLastPreprocessDurationMs),
        ("avg_encoded_frame_bytes={0}" -f $Summary.LatestAverageEncodedFrameBytes),
        ("displayable_frame_ratio={0}" -f $Summary.LatestDisplayableFrameRatio),
        ("normal_mode_summary_count={0}" -f $Summary.NormalModeSummaryCount),
        ("reduced_mode_summary_count={0}" -f $Summary.ReducedModeSummaryCount),
        ("catch_up_mode_summary_count={0}" -f $Summary.CatchUpModeSummaryCount),
        ("helper_surface_interpolation_mode={0}" -f $Summary.LatestHelperSurfaceInterpolationMode),
        ("helper_surface_frame_width={0}" -f $Summary.LatestHelperSurfaceFrameWidth),
        ("helper_surface_frame_height={0}" -f $Summary.LatestHelperSurfaceFrameHeight),
        ("helper_surface_viewport_width={0}" -f $Summary.LatestHelperSurfaceViewportWidth),
        ("helper_surface_viewport_height={0}" -f $Summary.LatestHelperSurfaceViewportHeight),
        ("helper_surface_render_scaling={0}" -f $Summary.LatestHelperSurfaceRenderScaling),
        ("helper_surface_displayed_width_px={0}" -f $Summary.LatestHelperSurfaceDisplayedWidthPx),
        ("helper_surface_displayed_height_px={0}" -f $Summary.LatestHelperSurfaceDisplayedHeightPx),
        ("helper_surface_scale_ratio={0}" -f $Summary.LatestHelperSurfaceScaleRatio),
        '',
        'freshness_summary_lines:'
    ) + @($Summary.FreshnessSummaryLines) + @(
        '',
        'surface_interpolation_lines:'
    ) + @($Summary.SurfaceInterpolationLines)

    Set-Content -Path (Join-Path $artifactDir 'helper-decode-worker-summary.txt') -Value $helperDecodeWorkerSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-quality-summary.txt') -Value $helperQualitySummary
    Set-Content -Path (Join-Path $artifactDir 'helper-upstream-latency-summary.txt') -Value $helperUpstreamLatencySummary
    Set-Content -Path (Join-Path $artifactDir 'helper-ready-path-summary.txt') -Value $helperReadyPathSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-receive-path-summary.txt') -Value $helperReceivePathSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-bridge-ingress-summary.txt') -Value $helperBridgeIngressSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-nkn-receive-summary.txt') -Value $helperNknReceiveSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-ws-receive-summary.txt') -Value $helperWsReceiveSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-socket-receive-summary.txt') -Value $helperSocketReceiveSummary
    Set-Content -Path (Join-Path $artifactDir 'bridge-event-loop-summary.txt') -Value $bridgeEventLoopSummary
    Set-Content -Path (Join-Path $artifactDir 'bridge-media-send-summary.txt') -Value $bridgeMediaSendSummary
    Set-Content -Path (Join-Path $artifactDir 'bridge-transport-health-summary.txt') -Value $bridgeTransportHealthSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-frame-loss-epoch.txt') -Value $helperEpochLossSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-epoch-timeline.txt') -Value $helperEpochTimelineSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-reassembler-root-cause-summary.txt') -Value $helperReassemblerRootCauseSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-pressure-summary.txt') -Value $helperPressureSummary
    Set-Content -Path (Join-Path $artifactDir 'helper-recovery-investigation-summary.txt') -Value $helperRecoveryInvestigationSummary
    Set-Content -Path (Join-Path $artifactDir 'health-snapshot-summary.txt') -Value $healthSnapshotSummary
    Set-Content -Path (Join-Path $artifactDir 'quality-presentation-summary.txt') -Value $qualityPresentationSummary
    Set-Content -Path (Join-Path $artifactDir 'reduced-promotion-summary.txt') -Value $promotionSummary
    Set-Content -Path (Join-Path $artifactDir 'sender-cadence-summary.txt') -Value $senderCadenceSummary
    Set-Content -Path (Join-Path $artifactDir 'recovery-burst-summary.txt') -Value $recoveryBurstSummary
    Set-Content -Path (Join-Path $artifactDir 'transport-mode-summary.txt') -Value $transportModeSummary

    return $artifactDir
}
